apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: video-manager-hpa
  namespace: default-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-manager-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80