apiVersion: v1
kind: Service
metadata:
  name: video-manager-service
  namespace: default-namespace
spec:
  selector:
    app: video-manager-hackaton
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer