apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-manager-deployment
  namespace: default-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-manager-hackaton
  template:
    metadata:
      labels:
        app: video-manager-hackaton
    spec:
      containers:
        - name: video-manager-hackaton
          image: matheuspatricio0/video-manager-hackaton:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          env:
            - name: KEYCLOAK_BASE_URL
              value: ${{ secrets.KEYCLOAK_BASE_URL }}
            - name: AWS_ACCESS_KEY_ID
              value: ${{ secrets.AWS_ACCESS_KEY_ID }}
            - name: AWS_SECRET_ACCESS_KEY
              value: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            - name: AWS_REGION
              value: ${{ secrets.AWS_REGION }}
            - name: KAFKA_SERVER
              value: ${{ secrets.KAFKA_SERVER }}
